name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libgl1 libsm6 libxext6 curl
            curl -L https://github.com/bluenviron/mediamtx/releases/download/v1.13.1/mediamtx_v1.13.1_linux_amd64.tar.gz -o mediamtx.tar.gz
          sudo tar -xzf mediamtx.tar.gz mediamtx
          sudo mv mediamtx /usr/local/bin/
          rm mediamtx.tar.gz

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo 'source "$HOME/.rye/env"' >> ~/.profile
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          rye sync --no-lock

      - name: Run tests
        run: |
          rye run pytest -vv
