name: docker-build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/shims" >> "$GITHUB_PATH"
      - name: Sync dependencies
        run: rye sync --no-lock
      - name: Build wheel
        run: rye build --wheel --clean
      - name: Build Docker image
        run: docker build --build-context dist=dist -t gack .
